name: CI Pipeline for Backend Testing

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root
          POSTGRES_DB: dev-EMS
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    env:
      POSTGRES_PRISMA_URL: "postgresql://root:root@localhost:5432/dev-EMS"
      POSTGRES_URL_NON_POOLING: "postgresql://root:root@localhost:5432/dev-EMS"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./packages/backend

      - name: Set up Prisma
        run: npx prisma generate
        working-directory: ./packages/backend

      - name: Run migrations
        run: npx prisma migrate dev
        working-directory: ./packages/backend

      - name: Run tests
        run: npm test
        working-directory: ./packages/backend
